### ISSUE TITLE
ExtensionMethodImageSource has Invalid type

### ISSUE THREAD

**Issue by cuiliang** [jbe2277/dotnetpad#16]
Hi, just find this:

https://github.com/jbe2277/dotnetpad/blob/e9e05369df2513739a1162118926cf5e48013b6d/src/DotNetPad/DotNetPad.Presentation/Resources/ImageResources.xaml#L180

should be wrapped in DrawingImage.

Thank you.

**Comment by jbe2277** [comment]
Thank's for reporting this issue. The fix will be included in the next release.
