### ISSUE TITLE
Can't use the keyboard to move the Output window

### ISSUE THREAD

**Issue by adamzuckerman** [jbe2277/dotnetpad#2]
In version 2.0.0.100, when you click in the Output tab, you can no longer move the contents of the window by used the cursor keys.  The mouse wheel does allow scrolling.

**Comment by adamzuckerman** [comment]
This also occurs in 2.0.1.100.

**Comment by jbe2277** [comment]
Thank you for the feedback. This behavior is since I set the Output tab readonly (about v1.2). Before it was possible to edit the text in the output tab (another bug). But the editing allowed to have a text cursor which could be moved via the keyboard.

**Comment by adamzuckerman** [comment]
You can still select text using the `Shift` key and the appropriate cursor keys.

**Comment by jbe2277** [comment]
I agree that it should still work to scroll by using the cursor keys. Unfortunately, this is an issue of the Microsoft RichTextBox component. It would be possible to find a workaround but I focus on more important features and issues at the moment.
