### ISSUE TITLE
Enhancement proposal -  Extend the "using" to all dotnet native libraries + reference external libraries

### ISSUE THREAD

**Issue by labichea** [jbe2277/dotnetpad#20]
The aim is to have access to the full dotnet native libraries + some external ones.

For external ones , scanning all librairies on a newly created ".\libraries"  folder where dotnetpad.exe is.

Code proposal 

ScriptingWorkspace.cs - line 66

references.Add(CreateReference(Assembly.Load("System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")));__
```
 **// Alexandre LABICHE - Load all native dll + external ones in .\libraries
 string baseNETCoreDLL = @"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\" + Environment.Version;
 if (Directory.Exists(baseNETCoreDLL))
 {
     string[] files = Directory.GetFiles(baseNETCoreDLL, "*.dll", SearchOption.TopDirectoryOnly);
     Assembly assembly;
     foreach (string file in files)
     {
         try
         {
             assembly = Assembly.LoadFrom(file);
             references.Add(CreateReference(assembly));
         }
         catch (Exception ex) { }
     }
 }
 string baseWindowsDesktopDLL = @"C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\" + Environment.Version;
 if (Directory.Exists(baseWindowsDesktopDLL))
 {
     string[] files = Directory.GetFiles(baseWindowsDesktopDLL, "*.dll", SearchOption.TopDirectoryOnly);
     Assembly assembly;
     foreach (string file in files)
     {
         try
         {
             assembly = Assembly.LoadFrom(file);
             references.Add(CreateReference(assembly));
         }
         catch (Exception ex) { }
     }
 }
 string baseFolder = AppDomain.CurrentDomain.BaseDirectory;
 if (Directory.Exists(baseFolder + @"\libraries"))
 {
     string[] files = Directory.GetFiles(baseFolder + @"\libraries", "*.dll", SearchOption.AllDirectories);
     Assembly assembly;
     foreach (string file in files)
     {
         assembly = Assembly.LoadFrom(file);
         references.Add(CreateReference(assembly));
     }
 }
 // Alex - End of section**
```

if (language == LanguageNames.VisualBasic) { references.Add(CreateReference(typeof(VBMath).Assembly)); }

**Comment by jbe2277** [comment]
Thank you for the suggestion.

The application does not depend on a installed SDK - it even works if no .NET SDK is installed at all. Therefore, I will not introduce code that tries to load all dlls from a SDK folder.

**Comment by labichea** [comment]
Where do you see that I am loading any SDK library ? As I am just extending the search at the same place of  the (too ?) few libraries you introspect ? 

I understand that you probably want to lockdown your app (for an unclear reason ? ) as the code to allow the full set of native dotnet libraries is so easy.

Thanks anyway, it,s an interesting product. Bye.
