### ISSUE TITLE
Pre-built executables for offline environment

### ISSUE THREAD

**Issue by vijayganeshpk** [jbe2277/dotnetpad#5]
Thank you for the app!
It would be great if you can also publish the compiled binaries so that we can use the app in offline environments.

**Comment by jbe2277** [comment]
Thanky you for your feedback. I will consider publishing the binary files as ZIP file for offline environments.

However, you could also download the files here:
https://github.com/jbe2277/dotnetpad/tree/gh-pages/clickonce

Run `DotNetPad.application` to start the application.

**Comment by mrexodia** [comment]
You could use https://www.appveyor.com and include the `out\Release` directory as an artifact of the build.
