### ISSUE TITLE
When number of lines increase typing is getting slow

### ISSUE THREAD

**Issue by backlune** [jbe2277/dotnetpad#6]
Hi,

First of all I like the editor a lot.

I've found that when the number of lines increase typing slows done a lot. For example typing fast on line 80 it takes long before all text is rendered.

I have dug in to the issue to try to fix it and made a commit to our master branch. Noticed now that you are not ready for contributions but if you want to have a look. Checkout: 0978d453fc5bed826fd948ae49054a4af6abb367

**Comment by jbe2277** [comment]
Thank you very much for giving me detailed information about this performance issue. Your commit was of much value as it helped me to understand this issue in no time.

**Comment by jbe2277** [comment]
Fixed in release [v2.2.1](https://github.com/jbe2277/dotnetpad/releases/tag/v2.2.1)

**Comment by backlune** [comment]
Great! Liked the way you structured the code.
